- project:
    templates:
      - docs-on-readthedocs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
    vars:
      rtd_webhook_id: '47125'
      rtd_project_name: pyshaker
    check:
      jobs:
        - openstack-tox-docs
    gate:
      jobs:
        - openstack-tox-docs

